on:
  push:
    tags:
      - "*"
name: Build and deploy release
jobs:
  build_public:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean package
      - uses: mdallasanta/ssh-scp-deploy@{version}
        with:
          local: "./target/ghs-server-${{github.ref_name}}.jar"
          remote: "~/ghs-server.jar"
          host: ${{secrets.HOST}}
          port: ${{secrets.PORT}}
          user: ${{secrets.USER}}
          key: ${{secrets.KEY}}
          pre_upload: ${{secrets.PRE_UPLOAD}}
          post_upload: ${{secrets.POST_UPLOAD}}sudo systemctrl start ghs-server.service
          ssh_options: -o StrictHostKeyChecking=no
