name: "Publish Docker Image"

on:
  push:
    tags:
      - 'v*'

env:
  SLUG_DOCKERHUB: ${{ secrets.DOCKER_USERNAME }}/ghs-server
  SLUG_GHCR: ghcr.io/${{ github.repository_owner }}/ghs-server
  SLUG_TEST: ghcr.io/Lurkars/ghs-server:v0.30.2

jobs:
  build-and-publish-docker-image:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      -
        name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.SLUG_DOCKERHUB }}
            ${{ env.SLUG_GHCR }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }} # automatic: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
      -
        name: Lowercase GHCR repository name # required because docker doesn't support uppercase chars: https://github.com/docker/build-push-action/issues/37
        run: |
          echo "SLUG_GHCR_LC=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Inspect Image published to Docker
        run: |
          docker pull "${{ env.SLUG_DOCKERHUB }}:${{ steps.meta.outputs.version }}"
          docker image inspect "${{ env.SLUG_DOCKERHUB }}:${{ steps.meta.outputs.version }}"
          docker pull "gloomhavensecretariat/ghs-server"
          docker image inspect "gloomhavensecretariat/ghs-server"
      -
        name: Inspect Image published to GHCR
        run: |
          docker pull "${{ env.SLUG_GHCR }}:${{ steps.meta.outputs.version }}"
          docker image inspect "${{ env.SLUG_GHCR }}:${{ steps.meta.outputs.version }}"
      -
        name: Test Lowercase GHCR repository name # required because docker doesn't support uppercase chars: https://github.com/docker/build-push-action/issues/37
        run: |
          echo "SLUG_TEST_LC=${TO_CONVERT,,}" >>${GITHUB_ENV}
        env:
          TO_CONVERT: '${{ env.SLUG_TEST }}'
      -
        name: Test for GHCR
        run: |
          docker pull ${{ SLUG_TEST_LC }}
          docker image inspect ${{ SLUG_TEST_LC }}
